name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-latest, windows-latest]
        include:
          - os: ubuntu-24.04
            cmake_generator: "Ninja"
            container: ubuntu:24.04
          - os: macos-latest
            cmake_generator: "Ninja"
          - os: windows-latest
            cmake_generator: "Ninja"

    container: ${{ matrix.container }}

    steps:
    - uses: actions/checkout@v4

    - name: Install build dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-24.04'
      run: |
        apt-get update
        apt-get install -y cmake ninja-build build-essential git
        # Try to install the latest available clang-tidy
        for version in 20 19 18 17 16; do
          if apt-get install -y clang-tidy-${version} 2>/dev/null; then
            echo "Installed clang-tidy-${version}"
            ln -sf $(which clang-tidy-${version}) /usr/local/bin/clang-tidy
            break
          fi
        done
        # Fallback to default clang-tidy
        if ! command -v clang-tidy &> /dev/null; then
          apt-get install -y clang-tidy
        fi
        clang-tidy --version

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install cmake ninja llvm
        echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH
        echo "/usr/local/opt/llvm/bin" >> $GITHUB_PATH

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        # Assuming Gitea runners have chocolatey installed
        choco install cmake ninja llvm --yes
        echo "C:\Program Files\LLVM\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Configure CMake
      shell: bash
      run: |
        echo "Current directory: $PWD"
        echo "Setting CMAKE_INSTALL_PREFIX to: $PWD/build/install"
        cmake -B build \
          -G "${{ matrix.cmake_generator }}" \
          -Dclang-tidy.cmake_BUILD_TESTS=ON \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -DCMAKE_INSTALL_PREFIX="$PWD/build/install"

    - name: Build
      run: cmake --build build

    - name: Test
      working-directory: build
      run: ctest --output-on-failure --verbose